// Reactivity/vue-reactivity/src/components/Counter.vue
<script setup lang="ts">
  import { computed, watchEffect } from 'vue'

  const props = defineProps<{
    value: number
  }>()

  console.log('Vue component rendered')

  const varDouble = props.value * 2
  const fnDouble = () => props.value * 2
  const computedDouble = computed(() => props.value * 2)

  let watchDouble = props.value * 2
  watchEffect(() => {
    watchDouble = props.value * 2
  })
</script>

<template>
  <div class="greetings">
    <h1 class="green">Vue prop reactivity</h1>
    <h3>
      Value (<code>prop</code>): <strong>{{ value }}</strong>
    </h3>
    <h3>
      Double (<code>const</code>):
      <strong style="color: #f13a3a; font-weight: bold">{{ varDouble }}</strong>
    </h3>
    <h3>
      Double (<code>function</code>): <strong>{{ fnDouble() }}</strong>
    </h3>
    <h3>
      Double (<code>computed</code>): <strong>{{ computedDouble }}</strong>
    </h3>
    <h3>
      Double (<code>watchEffect</code>): <strong>{{ watchDouble }}</strong>
    </h3>
  </div>
</template>

// Reactivity/react-reactivity/src/Counter.tsx
import { useEffect, useMemo } from "react";

export function Counter({ value }: { value: number }) {
  console.log("React component rendered");

  const varDouble = value * 2;
  const fnDouble = () => value * 2;
  const memoedDouble = useMemo(() => value * 2, [value]);

  let effectDouble = value * 2;
  useEffect(() => {
    effectDouble = value * 2;
  }, [value]);

  return (
    <div className="greetings">
      <h1 className="green">React prop reactivity</h1>
      <h3>
        Value (<code>prop</code>): <strong>{value}</strong>
      </h3>
      <h3>
        Double (<code>const</code>): <strong>{varDouble}</strong>
      </h3>
      <h3>
        Double (<code>function</code>): <strong>{fnDouble()}</strong>
      </h3>
      <h3>
        Double (<code>useMemo</code>): <strong>{memoedDouble}</strong>
      </h3>
      <h3>
        Double (<code>usehEffect</code>): <strong>{effectDouble}</strong>
      </h3>
    </div>
  );
}
